version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["nginx", "-g", "daemon off;"]  # Override the default command to run nginx
    ports:
      - "80:80"
